version: '3.1'

services:

  wordpress:
    image: wordpress
    user: "1000:1000"
    sysctls:
      net.ipv4.ip_unprivileged_port_start: 0
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - .tmp/wordpress:/var/www/html

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_ROOT_PASSWORD: root 
    volumes:
      - .tmp/db:/var/lib/mysql

volumes:
  wordpress:
  db:
